### PR TITLE
Added Boss Backend page

### LINKED ISSUE #21: make a page about this project on lab.codingblocks.com
check for reference how to add a new project - https://github.com/coding-blocks/lab.codingblocks.com/pull/7

### PR DESCRIPTION
**Pull request by bhavyaagg**
fixes coding-blocks/boss-backend#21.

### CODE REVIEW

**Comment by bhavyaagg** [comment]
@championswimmer please review and merge.

**Comment by bhavyaagg** [comment]
@championswimmer bhaiya you merged #16 although this pr was created 9 days ago.

**Comment by omerjerk** [comment]
@championswimmer You merged 2 pull requests for the same issue?

**Comment by championswimmer** [comment]
yeah, my bad

**Pull request merged**
